export type Record = {
  id: string;
  First_Name: string;
  Last_Name: string;
  Marksheet_Image: string;
  Board: string;
  Date_of_Birth: string;
  Guardian_Name: string;
  Roll: string;
  School: string;
  CGPA_Result: string;
  Accountancy?: string;
  Biology?: string;
  Business?: string;
  Chemistry?: string;
  Computer?: string;
  Economics?: string;
  English?: string;
  Mathematics?: string;
  Physical?: string;
  Physics?: string;
};
